name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      systems:
        description: 'CSV of systems to deploy to'
        required: true
jobs:
  generate-systems-list:
    runs-on: ubuntu-latest
    outputs:
      systems: ${{ steps.generate-system.outputs.systems }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: generate-system
        name: Generate system
        run: |
          echo "::set-output name=systems::$(node deployments.js)"
        env:
          DEPLOY_SYSTEMS: ${{ inputs.systems }}
  deploy:
    runs-on: ubuntu-latest
    needs: generate-systems-list
    strategy:
      matrix:
        system: ${{ fromJson(needs.generate-systems-list.outputs.systems) }}
    steps:
      - name: Show systems
        id: generate-system
        run: echo ${{matrix.system.name}} ${{matrix.system.domain}}